name: Travis Video
favicon: null
layout_spectrum: 0.17495323764160275
typography_spectrum: 0.2951580178923905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6162796812132001
  lightness: 0.4648676021024585
  saturation: 0.5774714350700378
  rhythmicContrast: 0.8916619019582868
purpose: []
